/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChecksRouteImport } from './routes/checks'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MarketRouteImport } from './routes/market'
import { Route as SendRouteImport } from './routes/send'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as CCodeRouteImport } from './routes/c.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksRoute = ChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const CCodeRoute = CCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checks': typeof ChecksRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/market': typeof MarketRoute
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/withdraw': typeof WithdrawRoute
  '/c/$code': typeof CCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checks': typeof ChecksRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/market': typeof MarketRoute
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/withdraw': typeof WithdrawRoute
  '/c/$code': typeof CCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checks': typeof ChecksRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/market': typeof MarketRoute
  '/send': typeof SendRoute
  '/swap': typeof SwapRoute
  '/withdraw': typeof WithdrawRoute
  '/c/$code': typeof CCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checks'
    | '/deposit'
    | '/history'
    | '/market'
    | '/send'
    | '/swap'
    | '/withdraw'
    | '/c/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/checks'
    | '/deposit'
    | '/history'
    | '/market'
    | '/send'
    | '/swap'
    | '/withdraw'
    | '/c/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checks'
    | '/deposit'
    | '/history'
    | '/market'
    | '/send'
    | '/swap'
    | '/withdraw'
    | '/c/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChecksRoute: typeof ChecksRoute
  DepositRoute: typeof DepositRoute
  HistoryRoute: typeof HistoryRoute
  MarketRoute: typeof MarketRoute
  SendRoute: typeof SendRoute
  SwapRoute: typeof SwapRoute
  WithdrawRoute: typeof WithdrawRoute
  CCodeRoute: typeof CCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checks': {
      id: '/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof ChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$code': {
      id: '/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof CCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChecksRoute: ChecksRoute,
  DepositRoute: DepositRoute,
  HistoryRoute: HistoryRoute,
  MarketRoute: MarketRoute,
  SendRoute: SendRoute,
  SwapRoute: SwapRoute,
  WithdrawRoute: WithdrawRoute,
  CCodeRoute: CCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
